### PR TITLE
feat: Starting the 2023 information

### PR DESCRIPTION
**Pull request by kf6kjg**

### CODE REVIEW

**Review by cwright248 — APPROVED** [review]
Looks great so far! 
Of course, we can consider the changes Kacie mentioned: I'd say the live stream/modesty statement seems to fit best in the Pricing and Side notes section. But, the location's weather is mentioned in the other section...
Speakers' names are spelled incorrectly as Kacie mentioned: The correct spelling seems to be Aron Crews and K'dee Elsen.
This one is kind of nit-picky, but perhaps the first line of the directions could be more concise: "has been proven accurate" or "has proven to be accurate" perhaps.
On line 326, it looks like a picture of Paul Coneff was added. Was he going to be there this year?

**Comment by kf6kjg** [comment]
Now with all the speakers!

**Comment by kf6kjg** [comment]
Pulled Jerry's bio from the git history for 2019. I've not been provided bios for Aron or Stephen.

**Comment by kf6kjg** [comment]
Schedule draft based on https://docs.google.com/spreadsheets/d/1mZ_rFe4qA-qddHt7gp02eT_yW8I_UMSVL8ogdllys9w/edit#gid=0

**Comment by kf6kjg** [comment]
Now including Stephen's bio!

**Comment by kf6kjg** [comment]
@cwright248 Go ahead and review when you can. However I need to make sure this is active tonight, so I'm merging.

**Review by cwright248 — COMMENTED** [review]
Everything looks good here!

**Review by cwright248 — COMMENTED** [review]
Everything looks fine on here too.

**Pull request merged**
